<section class="mt-3 card card-body">
    <h1>Gerenciar Catigurías</h1>

    <div class="mt-2">
        <a href="/categorias/novo" class="btn btn-outline-dark">Nova Catiguría</a>

        <a href="/categorias/relatorio" target="_blank" class="btn btn-outline-dark">Gerar PDF</a>
    </div>

    <table class="table table-striped table-hover mt-4">
        <thead class="table-dark">
            <tr>
                <th>#ID</th>
                <th>Nome</th>
                <th>Ações</th>
            </tr>
        </thead>
        <tbody>
            <?php
                    foreach ($categorias ?? [] as $categoria) {
                        echo "
                            <tr>
                                <td>{$categoria->id}</td>
                                <td>{$categoria->nome}</td>
                                <td>
                                    <a href='/categorias/editar?id={$categoria->id}' class='btn btn-outline-warning btn-sm'>Editar</a>
                                    <a href='/categorias/excluir?id={$categoria->id}' class='btn btn-outline-danger btn-sm'>Excluir</a>
                                </td>
                            </tr>
                        ";
                    }
                // }
            ?>
        </tbody>
    </table>
</section>