
<section class="mt-3 card card-body">
    <h1>Gerenciar Categoria</h1>

    <div class="mt-2">
        <a href="/categorias/novo" class="btn btn-outline-dark">Nova Categoria</a>
        
        <a href="/categorias/relatorio" target="_blank" class="btn btn-outline-dark">Gerar PDF</a>
    </div>

    <table class="table table-striped table-hover mt-4">
        <thead class="table-dark">
            <tr>
                <th>#ID</th>
                <th>Nome</th>
            </tr>
        </thead>
        <tbody>
            <?php
                if(isset($categorias) && sizeOf($categorias) > 0){
                    foreach ($categorias as $categoria) {
                        echo "
                            <tr>
                                <td>{$categoria['curso_id']}</td>
                                <td>{$categoria['curso_nome']}</td>
                                <td>
                                    <a href='/categorias/editar?id={$categoria['curso_id']}' class='btn btn-warning'>Editar</a>
                                    <a href='/categorias/excluir?id={$categoria['curso_id']}' class='btn btn-danger'>Deletar</a>
                                </td>
                            </tr>
                        ";
                    }
                }
            ?>
        </tbody>
    </table>
</section>